a=int(input("enter number:"))
b=int(input("enter number:"))
print("addition=" ,a+b)
print("subtraction=" ,a-b)
print("division=" ,a/b)
print("multiplication=" ,a*b)
print("integer division=" ,a//b)
print("exponent=" ,a**b)